{
 "title": "SP1 Cluster Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "query": {
     "query": "label_values(spn_info,environment)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(spn_cluster_worker_num_gpu_workers{environment=~\"${environment:regex}\"},cluster_name)"
    }
   },
   {
    "name": "fulfiller",
    "query": {
     "query": "label_values(spn_exporter_proof_gas_millions,fulfiller)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(spn_cluster_worker_num_gpu_workers{cluster_name=~\"${cluster:regex}\",environment=~\"${environment:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(spn_cluster_worker_num_gpu_workers{cluster_name=~\"${cluster:regex}\",environment=~\"${environment:regex}\"})-sum(spn_cluster_worker_num_gpu_workers{cluster_name=~\"${cluster:regex}\",environment=~\"${environment:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(spn_cluster_worker_num_gpu_workers{cluster_name=~\"${cluster:regex}\",environment=~\"${environment:regex}\"})-sum(spn_cluster_worker_num_gpu_workers{cluster_name=~\"${cluster:regex}\",environment=~\"${environment:regex}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proofs Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(spn_cluster_worker_task_successes{environment=~\"${environment:regex}\", cluster_name=~\".*${cluster:regex}\",task_type=\"CONTROLLER\"}[30m]))",
     "legendFormat": "Completed Proofs"
    }
   ]
  },
  {
   "title": "Active GPUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(sum(spn_cluster_worker_gpu_busy_time{environment=~\"${environment:regex}\",cluster_name=~\".*$cluster\"}>0)[$__rate_interval:])/1000",
     "legendFormat": "Estimated Active GPUs"
    },
    {
     "expr": "sum(spn_cluster_worker_num_gpu_workers{environment=~\"${environment:regex}\",cluster_name=~\".*$cluster\"})",
     "legendFormat": "GPUs"
    }
   ]
  },
  {
   "title": "Worker Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(spn_cluster_worker_memory_usage_percent{environment=~\"${environment:regex}\", cluster_name=~\".*${cluster:regex}\"}) by (container_name)",
     "legendFormat": "{{container_name}} max"
    },
    {
     "expr": "avg(spn_cluster_worker_memory_usage_percent{environment=~\"${environment:regex}\", cluster_name=~\".*${cluster:regex}\"}) by (container_name)",
     "legendFormat": "{{container_name}} avg"
    },
    {
     "expr": "min(spn_cluster_worker_memory_usage_percent{environment=~\"${environment:regex}\", cluster_name=~\".*${cluster:regex}\"}) by (container_name)",
     "legendFormat": "{{container_name}} min"
    }
   ]
  },
  {
   "title": "Total Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(spn_cluster_worker_tasks_in_progress{environment=~\"${environment:regex}\", cluster_name=~\".*${cluster:regex}\"}) by (task_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Task Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg(spn_cluster_worker_task_processing_duration_ms{environment=~\"${environment:regex}\", cluster_arn=~\".*${cluster:regex}\", task_type!=\"SP1_CONTROLLER\"}) by (task_type)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}