[package]
name = "sp1-cluster-bidder"
version = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[dependencies]
spn-metrics = { workspace = true }
spn-network-types = { workspace = true, features = ["network"] }
spn-utils = { workspace = true }

alloy = { workspace = true }
alloy-signer-local = { workspace = true }
anyhow = { workspace = true }
config = { workspace = true }
dotenv = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
