#!/bin/sh

export NODE_COORDINATOR_RPC=http://127.0.0.1:50053
export NODE_ARTIFACT_STORE=redis
export NODE_REDIS_NODES=redis://:redispassword@127.0.0.1:6379/0
export WORKER_TYPE=ALL
export TRACING_ENABLED=true
export SP1_WORKER_NUM_SPLICING_WORKERS=12
export SP1_WORKER_SPLICING_BUFFER_SIZE=12
export WORKER_MAX_WEIGHT_OVERRIDE=24
export SP1_WORKER_NUMBER_OF_SEND_SPLICE_WORKERS_PER_SPLICE=4
export SP1_WORKER_SEND_SPLICE_INPUT_BUFFER_SIZE_PER_SPLICE=4
export MINIMAL_TRACE_CHUNK_THRESHOLD=33554432
export WORKER_PLONK_WRAP_WEIGHT=14
export RUST_LOG=info,sp1-prover=info
export OTLP_ENDPOINT=http://127.0.0.1:4319
export PROOF_DURATIONS_CSV=data/proof_durations.csv

./target/release/sp1-cluster-node
